[project]
name = "dnn-inference-tjjd4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tensorflow>=2.19.0",
    "tensorflow-metal>=1.2.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
